import Foundation

// Detection-only stubs for Denon DJ, Numark, Hercules, Native Instruments,
// Allen & Heath, Mixars, Akai, and Novation hardware.
// Source policy: detection-only until official MIDI docs or open-source mappings are cited.
// Do NOT claim official support, endorsement, or affiliation with any manufacturer.

enum OtherDJProfiles {

    static var stubs: [ControllerProfile] {
        denonStubs + numarkStubs + herculesStubs + niStubs + ahStubs + otherStubs
    }

    // MARK: - Denon DJ

    private static let denonStubs: [ControllerProfile] = [
        ControllerProfile(
            id: "denon.sc6000m",
            internalManufacturer: "Denon DJ / inMusic",
            internalModel: "SC6000M",
            publicDisplayFamily: "Media Player",
            matchNames: ["SC6000M", "Denon SC6000M", "SC6000 M"],
            deviceNameRegexes: [],
            profileKind: .mediaPlayer,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 1, physicalDeckCount: 1,
            bindings: [], verificationSteps: [],
            assumptions: ["Motorized media player. MIDI platter stream not yet sourced."],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "denon.sc6000",
            internalManufacturer: "Denon DJ / inMusic",
            internalModel: "SC6000",
            publicDisplayFamily: "Media Player",
            matchNames: ["SC6000"],
            deviceNameRegexes: [],
            profileKind: .mediaPlayer,
            deviceClass: .detectionOnly,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 1, physicalDeckCount: 1,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "denon.sc5000m",
            internalManufacturer: "Denon DJ / inMusic",
            internalModel: "SC5000M",
            publicDisplayFamily: "Media Player",
            matchNames: ["SC5000M", "SC5000 M"],
            deviceNameRegexes: [],
            profileKind: .mediaPlayer,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 1, physicalDeckCount: 1,
            bindings: [], verificationSteps: [],
            assumptions: ["Motorized media player."],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "denon.sc5000",
            internalManufacturer: "Denon DJ / inMusic",
            internalModel: "SC5000",
            publicDisplayFamily: "Media Player",
            matchNames: ["SC5000"],
            deviceNameRegexes: [],
            profileKind: .mediaPlayer,
            deviceClass: .detectionOnly,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 1, physicalDeckCount: 1,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "denon.prime4plus",
            internalManufacturer: "Denon DJ / inMusic",
            internalModel: "Prime 4+",
            publicDisplayFamily: "Standalone DJ System",
            matchNames: ["Prime 4+", "Prime4Plus"],
            deviceNameRegexes: [],
            profileKind: .standaloneDJSystem,
            deviceClass: .detectionOnly,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 4, physicalDeckCount: 4,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "denon.prime4",
            internalManufacturer: "Denon DJ / inMusic",
            internalModel: "Prime 4",
            publicDisplayFamily: "Standalone DJ System",
            matchNames: ["Prime 4"],
            deviceNameRegexes: [],
            profileKind: .standaloneDJSystem,
            deviceClass: .detectionOnly,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 4, physicalDeckCount: 4,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "denon.prime-go-plus",
            internalManufacturer: "Denon DJ / inMusic",
            internalModel: "Prime Go+",
            publicDisplayFamily: "Standalone DJ System",
            matchNames: ["Prime Go+", "Prime Go Plus"],
            deviceNameRegexes: [],
            profileKind: .standaloneDJSystem,
            deviceClass: .detectionOnly,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "denon.prime-go",
            internalManufacturer: "Denon DJ / inMusic",
            internalModel: "Prime Go",
            publicDisplayFamily: "Standalone DJ System",
            matchNames: ["Prime Go"],
            deviceNameRegexes: [],
            profileKind: .standaloneDJSystem,
            deviceClass: .detectionOnly,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "denon.mixstream-pro-plus",
            internalManufacturer: "Denon DJ / inMusic",
            internalModel: "Mixstream Pro+",
            publicDisplayFamily: "Standalone DJ System",
            matchNames: ["Mixstream Pro+", "Mixstream Pro Plus"],
            deviceNameRegexes: [],
            profileKind: .standaloneDJSystem,
            deviceClass: .detectionOnly,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "denon.mixstream-pro",
            internalManufacturer: "Denon DJ / inMusic",
            internalModel: "Mixstream Pro",
            publicDisplayFamily: "Standalone DJ System",
            matchNames: ["Mixstream Pro"],
            deviceNameRegexes: [],
            profileKind: .standaloneDJSystem,
            deviceClass: .detectionOnly,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "denon.mcx8000",
            internalManufacturer: "Denon DJ / inMusic",
            internalModel: "MCX8000",
            publicDisplayFamily: "Standalone DJ System",
            matchNames: ["MCX8000", "Denon MCX8000"],
            deviceNameRegexes: [],
            profileKind: .standaloneDJSystem,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 4, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "denon.mc7000",
            internalManufacturer: "Denon DJ / inMusic",
            internalModel: "MC7000",
            publicDisplayFamily: "4-Channel Performance Controller",
            matchNames: ["MC7000", "Denon MC7000"],
            deviceNameRegexes: [],
            profileKind: .fourChannelPerformanceController,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 4, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
    ]

    // MARK: - Numark

    private static let numarkStubs: [ControllerProfile] = [
        ControllerProfile(
            id: "numark.ns7iii",
            internalManufacturer: "Numark / inMusic",
            internalModel: "NS7III",
            publicDisplayFamily: "Motorized Platter Controller",
            matchNames: ["NS7III", "NS7 III", "Numark NS7III"],
            deviceNameRegexes: [],
            profileKind: .motorizedPlatterController,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 4, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: ["Motorized jog wheels. MIDI platter stream not yet sourced."],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "numark.ns7ii",
            internalManufacturer: "Numark / inMusic",
            internalModel: "NS7II",
            publicDisplayFamily: "Motorized Platter Controller",
            matchNames: ["NS7II", "NS7 II", "Numark NS7II"],
            deviceNameRegexes: [],
            profileKind: .motorizedPlatterController,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 4, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: ["Motorized jog wheels."],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "numark.ns6ii",
            internalManufacturer: "Numark / inMusic",
            internalModel: "NS6II",
            publicDisplayFamily: "4-Channel Performance Controller",
            matchNames: ["NS6II", "NS6 II", "Numark NS6II"],
            deviceNameRegexes: [],
            profileKind: .fourChannelPerformanceController,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 4, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "numark.mixtrack-pro-fx",
            internalManufacturer: "Numark / inMusic",
            internalModel: "Mixtrack Pro FX",
            publicDisplayFamily: "Compact DJ Controller",
            matchNames: ["Mixtrack Pro FX"],
            deviceNameRegexes: [],
            profileKind: .compactDJController,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "numark.mixtrack-platinum-fx",
            internalManufacturer: "Numark / inMusic",
            internalModel: "Mixtrack Platinum FX",
            publicDisplayFamily: "Compact DJ Controller",
            matchNames: ["Mixtrack Platinum FX"],
            deviceNameRegexes: [],
            profileKind: .compactDJController,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "numark.mixstream-pro",
            internalManufacturer: "Numark / inMusic",
            internalModel: "Mixstream Pro",
            publicDisplayFamily: "Standalone DJ System",
            matchNames: ["Numark Mixstream Pro"],
            deviceNameRegexes: [],
            profileKind: .standaloneDJSystem,
            deviceClass: .detectionOnly,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
    ]

    // MARK: - Hercules

    private static let herculesStubs: [ControllerProfile] = [
        ControllerProfile(
            id: "hercules.inpulse-t7",
            internalManufacturer: "Hercules / Guillemot",
            internalModel: "DJControl Inpulse T7",
            publicDisplayFamily: "Motorized Platter Controller",
            matchNames: ["Inpulse T7", "DJControl Inpulse T7", "Hercules Inpulse T7"],
            deviceNameRegexes: [],
            profileKind: .motorizedPlatterController,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: ["Motorized jog wheels. MIDI platter stream not yet sourced."],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "hercules.inpulse-500",
            internalManufacturer: "Hercules / Guillemot",
            internalModel: "DJControl Inpulse 500",
            publicDisplayFamily: "Compact DJ Controller",
            matchNames: ["Inpulse 500", "DJControl Inpulse 500"],
            deviceNameRegexes: [],
            profileKind: .compactDJController,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "hercules.inpulse-300",
            internalManufacturer: "Hercules / Guillemot",
            internalModel: "DJControl Inpulse 300",
            publicDisplayFamily: "Compact DJ Controller",
            matchNames: ["Inpulse 300", "DJControl Inpulse 300"],
            deviceNameRegexes: [],
            profileKind: .compactDJController,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "hercules.inpulse-200",
            internalManufacturer: "Hercules / Guillemot",
            internalModel: "DJControl Inpulse 200",
            publicDisplayFamily: "Compact DJ Controller",
            matchNames: ["Inpulse 200", "DJControl Inpulse 200"],
            deviceNameRegexes: [],
            profileKind: .compactDJController,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
    ]

    // MARK: - Native Instruments

    private static let niStubs: [ControllerProfile] = [
        ControllerProfile(
            id: "ni.traktor-s4-mk3",
            internalManufacturer: "Native Instruments",
            internalModel: "Traktor Kontrol S4 MK3",
            publicDisplayFamily: "4-Channel Performance Controller",
            matchNames: ["Traktor Kontrol S4 MK3", "S4 MK3", "Kontrol S4"],
            deviceNameRegexes: [],
            profileKind: .fourChannelPerformanceController,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 4, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: ["Motorized jog wheels. MIDI/HID platter stream not yet sourced."],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "ni.traktor-s3",
            internalManufacturer: "Native Instruments",
            internalModel: "Traktor Kontrol S3",
            publicDisplayFamily: "4-Channel Performance Controller",
            matchNames: ["Traktor Kontrol S3", "S3", "Kontrol S3"],
            deviceNameRegexes: [],
            profileKind: .fourChannelPerformanceController,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 4, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "ni.traktor-s2",
            internalManufacturer: "Native Instruments",
            internalModel: "Traktor Kontrol S2",
            publicDisplayFamily: "2-Channel Battle Controller",
            matchNames: ["Traktor Kontrol S2", "Kontrol S2"],
            deviceNameRegexes: [],
            profileKind: .twoChannelBattleController,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "ni.traktor-z2",
            internalManufacturer: "Native Instruments",
            internalModel: "Traktor Kontrol Z2",
            publicDisplayFamily: "Battle Mixer",
            matchNames: ["Traktor Kontrol Z2", "Kontrol Z2"],
            deviceNameRegexes: [],
            profileKind: .battleMixer,
            deviceClass: .faderPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 0,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "ni.traktor-x1",
            internalManufacturer: "Native Instruments",
            internalModel: "Traktor Kontrol X1",
            publicDisplayFamily: "Detected MIDI Device",
            matchNames: ["Traktor Kontrol X1", "Kontrol X1"],
            deviceNameRegexes: [],
            profileKind: .compactDJController,
            deviceClass: .transportPadsOnly,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 0, physicalDeckCount: 0,
            bindings: [], verificationSteps: [],
            assumptions: ["Small add-on controller; no jog wheel."],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "ni.traktor-f1",
            internalManufacturer: "Native Instruments",
            internalModel: "Traktor Kontrol F1",
            publicDisplayFamily: "Detected MIDI Device",
            matchNames: ["Traktor Kontrol F1", "Kontrol F1"],
            deviceNameRegexes: [],
            profileKind: .compactDJController,
            deviceClass: .transportPadsOnly,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 0, physicalDeckCount: 0,
            bindings: [], verificationSteps: [],
            assumptions: ["Remix set pad controller; no jog wheel."],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "ni.traktor-z1",
            internalManufacturer: "Native Instruments",
            internalModel: "Traktor Kontrol Z1",
            publicDisplayFamily: "Detected MIDI Device",
            matchNames: ["Traktor Kontrol Z1", "Kontrol Z1"],
            deviceNameRegexes: [],
            profileKind: .compactDJController,
            deviceClass: .faderPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 0,
            bindings: [], verificationSteps: [],
            assumptions: ["Small mixer add-on; no jog wheel."],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
    ]

    // MARK: - Allen & Heath

    private static let ahStubs: [ControllerProfile] = [
        ControllerProfile(
            id: "allen-heath.xone-k2",
            internalManufacturer: "Allen & Heath",
            internalModel: "Xone:K2",
            publicDisplayFamily: "Detected MIDI Device",
            matchNames: ["Xone:K2", "Xone K2", "XoneK2"],
            deviceNameRegexes: [],
            profileKind: .compactDJController,
            deviceClass: .transportPadsOnly,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 0, physicalDeckCount: 0,
            bindings: [], verificationSteps: [],
            assumptions: ["Modular performance controller; no jog wheel. Fader/buttons only."],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "allen-heath.xone-px5",
            internalManufacturer: "Allen & Heath",
            internalModel: "Xone:PX5",
            publicDisplayFamily: "DJ Mixer",
            matchNames: ["Xone:PX5", "Xone PX5"],
            deviceNameRegexes: [],
            profileKind: .djMixer,
            deviceClass: .faderPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 4, physicalDeckCount: 0,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "allen-heath.xone-96",
            internalManufacturer: "Allen & Heath",
            internalModel: "Xone:96",
            publicDisplayFamily: "DJ Mixer",
            matchNames: ["Xone:96", "Xone 96"],
            deviceNameRegexes: [],
            profileKind: .djMixer,
            deviceClass: .faderPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 6, physicalDeckCount: 0,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "allen-heath.xone-23c",
            internalManufacturer: "Allen & Heath",
            internalModel: "Xone:23C",
            publicDisplayFamily: "DJ Mixer",
            matchNames: ["Xone:23C", "Xone 23C"],
            deviceNameRegexes: [],
            profileKind: .djMixer,
            deviceClass: .faderPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 0,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
    ]

    // MARK: - Mixars, Akai, Novation

    private static let otherStubs: [ControllerProfile] = [
        ControllerProfile(
            id: "mixars.duo",
            internalManufacturer: "Mixars",
            internalModel: "Duo",
            publicDisplayFamily: "2-Channel Battle Controller",
            matchNames: ["Mixars Duo"],
            deviceNameRegexes: [],
            profileKind: .twoChannelBattleController,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "mixars.quattro",
            internalManufacturer: "Mixars",
            internalModel: "Quattro",
            publicDisplayFamily: "4-Channel Performance Controller",
            matchNames: ["Mixars Quattro"],
            deviceNameRegexes: [],
            profileKind: .fourChannelPerformanceController,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 4, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "akai.amx",
            internalManufacturer: "Akai Professional / inMusic",
            internalModel: "AMX",
            publicDisplayFamily: "Battle Mixer",
            matchNames: ["Akai AMX"],
            deviceNameRegexes: [],
            profileKind: .battleMixer,
            deviceClass: .faderPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 0,
            bindings: [], verificationSteps: [],
            assumptions: [],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "akai.afx",
            internalManufacturer: "Akai Professional / inMusic",
            internalModel: "AFX",
            publicDisplayFamily: "Detected MIDI Device",
            matchNames: ["Akai AFX"],
            deviceNameRegexes: [],
            profileKind: .compactDJController,
            deviceClass: .transportPadsOnly,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 0, physicalDeckCount: 0,
            bindings: [], verificationSteps: [],
            assumptions: ["Pad/FX controller; no jog wheel."],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
        ControllerProfile(
            id: "novation.twitch",
            internalManufacturer: "Novation / Focusrite",
            internalModel: "Twitch",
            publicDisplayFamily: "2-Channel Battle Controller",
            matchNames: ["Novation Twitch"],
            deviceNameRegexes: [],
            profileKind: .twoChannelBattleController,
            deviceClass: .scratchPrimary,
            mappingStatus: .detectionOnly,
            sourceConfidence: .unknown,
            verificationRequired: true,
            deckCount: 2, physicalDeckCount: 2,
            bindings: [], verificationSteps: [],
            assumptions: ["Touch-strip jog; encoding and suitability for scratch capture not confirmed."],
            sourceNotes: "Detection stub only.", sourceURLs: [],
            lastCheckedDate: "2024-01-01"
        ),
    ]
}
